college_project/college_app/urls.py
from django.urls import path
from . import views

app_name = 'college_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('user_info/', views.user_info, name='user_info'),
    path('logout/', views.user_logout, name='logout'),
    path('enquiry/', views.enquiry, name='enquiry'),
    path('<slug:d_slug>/', views.dept_detail, name='department'),
]

college_project/college_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('college_app.urls')),
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

college_project/college_app/models.py
from django.db import models
from django.urls import reverse

class Department(models.Model):
    name=models.CharField(max_length=250, unique=True)
    slug=models.SlugField(max_length=250, unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='dept',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='department'
        verbose_name_plural='departments'
    
    def get_url(self):
        return reverse('college_app:department',args=[str(self.slug)])

    def __str__(self):
        return '{}'.format(self.name)

class Course(models.Model):
    name = models.CharField(max_length=255)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    class Meta:
        ordering=('name',)
        verbose_name='course'
        verbose_name_plural='courses'

    def __str__(self):
        return '{}'.format(self.name)
    
class Enquiry(models.Model):
    name = models.CharField(max_length=255)
    dob = models.DateField()
    age = models.IntegerField()
    gender = models.CharField(max_length=10)
    phoneNumber = models.CharField(max_length=15)
    mailId = models.EmailField()
    address = models.TextField()
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    courses = models.ForeignKey(Course, on_delete=models.CASCADE)
    purpose = models.CharField(max_length=255)
    materials = models.CharField(max_length=255)

    def __str__(self):
        return '{}'.format(self.name)

college_project/college_app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Department, Course, Enquiry
from django.contrib.auth.models import User
from django.contrib import messages,auth
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# Create your views here.
def home(request):
    obj=Department.objects.all()
    return render(request,'department.html',{'result':obj})

def register(request):
    if request.method=='POST':
        username= request.POST['username']
        email= request.POST['email']
        password= request.POST['password']
        confpass= request.POST['password1']
        if password==confpass:
            if User.objects.filter(username=username).exists():
                messages.info(request,"Username Taken..")
                return redirect('college_app:register')
            elif User.objects.filter(email=email).exists():
                messages.info(request,"Email already exists..")
                return redirect('college_app:register')
            else:
                user=User.objects.create_user(username=username,password=password,email=email)
                user.save()
                print("user created")
                return redirect('college_app:login')

        else:
            messages.info(request,"password not matching")
            return redirect('college_app:register')
    return render(request, 'register.html')

def user_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return render(request, 'userinfo.html') 
        else:
            messages.error(request, "Invalid credentials")
            return render(request, 'login.html')

    return render(request, 'login.html')

def user_logout(request):
    auth.logout(request)
    return redirect('/')

def enquiry(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        dob = request.POST.get('dob')
        age = request.POST.get('age')
        gender = request.POST.get('gender')
        phoneNumber = request.POST.get('phoneNumber')
        mailId = request.POST.get('mailId')
        address = request.POST.get('address')
        department_id = request.POST.get('department')
        course_id = request.POST.get('course')
        purpose = request.POST.get('purpose')
        materials = request.POST.getlist('materials')

        # Save the enquiry to the database
        enquiry = Enquiry.objects.create(
            name=name,
            dob=dob,
            age=age,
            gender=gender,
            phoneNumber=phoneNumber,
            mailId=mailId,
            address=address,
            department_id=department_id,
            course_id=course_id,
            purpose=purpose,
        )
        enquiry.materials.set(materials)

        # Redirect to a success page
        return redirect('success')

    else:
        departments = Department.objects.all()
        courses = Course.objects.all()
        return render(request, 'enquiry.html', {'departments': departments, 'courses': courses})

def success(request):
    return render(request, 'success.html')

def dept_detail(request, d_slug):
    department = get_object_or_404(Department, slug=d_slug)
    enquiries = Enquiry.objects.filter(department=department)
    return render(request, 'desc.html', {'department': department, 'enquiries': enquiries})

@login_required
def user_info(request):
    return render(request, 'userinfo.html')

college_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
        <meta name="description" content="{% block metadescription %}{% endblock %}">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <div class="container">
            {% include 'header.html' %}
            {% include 'navbar.html' %}<br>
            {% block content %}
            {% endblock %}
        </div>
        {% include 'footer.html' %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    </body>
</html>

        

college_project/templates/department.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {% if department %}
        {{ department.description|truncatewords:155 }}
    {% else %}
        Welcome to Muforl store to buy different things online
    {% endif %}
{% endblock %}

{% block title %}
    {% if department %}
        {{ department.name }} - Muforl Store
    {% else %}
        Welcome to Appolo University your stepping stones to the future
    {% endif %}
{% endblock %}

{% block content %}
<div class="mx-auto" style="height: 100vh;">
    {% if department %}
        <img class="my_image" src="{{ department.image.url }}" alt="{{ department.name }}" >
    </div>
    <br>
    <div>
        <h1 class="text-center my_title">{{ department.name }}</h1>
        <p class="text-justify">{{ department.description }}</p>
    </div>
    {% else %}
        <div>
            <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="our products" width="1110 px" >
        </div>
        <br>
        <div>
            <h1 class="text-center my_title">Introduction</h1><br>
            <p class="text-justify">Welcome to Apollo University of Science and Arts, where innovation meets intellect, and creativity converges with knowledge. At Apollo University, we pride ourselves on fostering a dynamic learning environment that transcends traditional boundaries, preparing our students for a future defined by cutting-edge advancements and a profound appreciation for the arts.

            Nestled at the intersection of science and arts, our institution is committed to cultivating a well-rounded education that empowers individuals to excel in their chosen fields while embracing the multidimensional nature of human expression. Apollo University stands as a beacon of academic excellence, where curiosity is nurtured, and the pursuit of knowledge is fueled by a passion for discovery.
            
            As you embark on your educational journey with us, you'll discover a community of forward-thinking educators, dedicated to guiding you through a transformative learning experience. Our state-of-the-art facilities, coupled with a diverse and vibrant campus culture, create an atmosphere that encourages collaboration, critical thinking, and the development of skills that extend beyond the classroom.
            
            Whether you are drawn to the precision of the sciences or the boundless creativity of the arts, Apollo University is committed to providing a platform for your unique talents to flourish. Join us on a voyage of intellectual exploration and artistic expression, where the Apollo community is united in its pursuit of knowledge, innovation, and a shared vision for a brighter future.
            
            Welcome to Apollo University, where the pursuit of excellence is not just a goal but a way of life.
            
            <!-- <br><div class="text-center">
                <a href="{% url 'college_app:register' %}" class="btn btn-success">Register</a> <a href="{% url 'college_app:login' %}" class="btn btn-success">Login</a>
            </div> -->
            </p><br><br>
        </div>
    {% endif %}
{% endblock %}

college_project/templates/desc.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    Details about the department is given in this page
{% endblock %}

{% block title %}
    {% if department %}
        {{ department.name }} - Apollo University
    {% endif %}
{% endblock %}

{% block content %}

        <div class="mx-auto">
            {% if department %}
                <img class="my_image" src="{{ department.image.url }}" alt="{{ department.name }}" style="width:1110px;">
            </div>
            <br>
            <div>
                <h1 class="text-center my_title">{{ department.name }}</h1><br>
                <p class="text-justify">{{ department.description }}</p>
            </div>
        {% endif %}
{% endblock %}

college_project/templates/enquiry.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    Welcome to Appolo University, your stepping stones to the future
{% endblock %}

{% block title %}
    Enquiry Form
{% endblock %}

{% block content %}
<style>
    .card-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh; /* Adjust as needed */
    }

    .card {
        width: 500px; /* Adjust as needed */
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .form-group {
        margin-bottom: 15px;
    }

    input,
    select,
    textarea {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        box-sizing: border-box;
    }
</style>

    </style>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <h2 class="card-title">Enquiry Page</h2>
            <form method="POST" action="{% url 'college_app:enquiry' %}">
                {% csrf_token %}

                <div class="form-group">
                    <label for="name">Name:</label><br>
                    <input type="text" id="name" name="name" required><br>
                </div>

                <div class="form-group">
                    <label for="dob">Date of Birth:</label><br>
                    <input type="date" id="dob" name="dob" required><br>
                </div>

                <div class="form-group">
                    <label for="age">Age:</label><br>
                    <input type="number" id="age" name="age" required><br>
                </div>

                <div class="form-group">
                    <label for="gender">Gender:</label><br>
                    <select id="gender" name="gender" required><br>
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                        <option value="other">Other</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="phoneNumber">Phone Number:</label><br>
                    <input type="tel" id="phoneNumber" name="phoneNumber" required><br>
                </div>
                <div class="form-group">
                    <label for="mailId">Email ID:</label><br>
                    <input type="email" id="mailId" name="mailId" required><br>
                </div>
                <div class="form-group">
                    <label for="address">Address:</label><br>
                    <textarea id="address" name="address" required></textarea><br>
                </div>
                <div class="form-group">
                    <label for="departments">Department:</label><br>
                    <select id="departments" name="department">
                        <option value="">Select Department</option>
                        {% for department in departments %}
                            <option value="{{ department.id }}">{{ department.name }}</option>
                        {% endfor %}
                    </select><br>
                </div>
                
                <div class="form-group">
                    <label for="courses">Course:</label><br>
                    <select id="courses" name="course">
                        <option value="">Select Course</option>
                        {% for course in courses %}
                            <option value="{{ course.id }}">{{ course.name }}</option>
                        {% endfor %}
                    </select><br>
                </div>
                
                <div class="form-group">
                    <label for="purpose">Purpose:</label><br>
                    <select id="purpose" name="purpose" required>
                        <option value="enquiry">For Enquiry</option>
                        <option value="order">Place Order</option>
                        <option value="return">Return</option>
                    </select><br>
                </div>
                <div class="form-group">
                    <label>Materials Provide:</label>
                    <input type="checkbox" id="notebook" name="materials" value="notebook">
                    <label for="notebook">Debit Note Book</label>
                
                    <input type="checkbox" id="pen" name="materials" value="pen">
                    <label for="pen">Documents</label>
            
                    <input type="checkbox" id="examPapers" name="materials" value="examPapers">
                    <label for="examPapers">Exam Papers</label>

                    <div class="button-section row mt-3">
                        <div class="col">
                            <input type="submit" class="btn btn-secondary btn-block" value="Submit">
                        </div>
                        <div class="col">
                            <button type="button" class="btn btn-secondary btn-block" onclick="logout()">Logout</button>
                        </div>
                    </div>
            </form>
        </div>
    </div>
</div>
</div>
</div><br><br>
{% endblock %}

college_project/templates/footer.html
<br><br><div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; Appolo University All rights reserved</p>
</div>

college_project/templates/header.html
{% load static %}
<header>
    <center>
        <a href= "{% url 'college_app:home' %}"><img src="{% static 'img/Appolo.png' %}" alt="logimage" height="150px"></a>
    </center>
</header><br>

college_project/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    This is the login page. Login to proceed further.
{% endblock %}

{% block title %}
    Login Page
{% endblock %}

{% block content %}
<div class="container" style="height: 100vh;">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <h2 class="card-title">Login Page</h2>
                    <form action="{% url 'college_app:login' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username:</label>
                            <input type="text" class="form-control" name="username" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Password:</label>
                            <input type="password" class="form-control" name="password" required>
                        </div>
                        <button type="submit" class="btn btn-primary" name="Login">Login</button>
                    </form><br>
                    <p>Not registered yet? <a href="{% url 'college_app:register' %}" alt="">Register now</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

college_project/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == 'college_app:home' %}active{% endif %}">
          <a class="nav-link" href="{% url 'college_app:home' %}"><i class="fa-solid fa-house"></i>
            <span class="sr-only">(current)</span></a>
      </li>
      <!-- <li class="nav-item {% if request.path == 'college_app:login' %}active{% endif %}">
          <a class="nav-link" href="{% url 'college_app:login' %}">Login<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == 'college_app:register' %}active{% endif %}">
          <a class="nav-link" href="{% url 'college_app:register' %}">Register<span class="sr-only">(current)</span></a>
      </li> -->
      <li class="nav-item dropdown {% if 'college_app' in request.path %}active{% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Department
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% for dept in links %}
          <a class="dropdown-item" href="{{dept.get_url}}">{{dept.name}}</a>
          <div class="dropdown-divider"></div>
          {% endfor %}
        </div>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      {% if user.is_authenticated %}
        <div class="text-center mx-auto">
          <p class="navbar-text my-0"><b>Hello, {{user.username}}</b></p>
        </div>
        <a href="{% url 'college_app:logout' %}"  style="margin-left:15px"><span class="material-symbols-outlined">
          logout
          </span></a>
      {% else %}
        <a href="{% url 'college_app:register' %}" class="btn btn-outline-secondary">Register</a>
        <a href="{% url 'college_app:login' %}"  style="margin-left: 15px;"><span class="material-symbols-outlined">
          login
          </span></a>
      {% endif %}
    </div>
  </div>
</nav>

college_project/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    Welcome to Appolo University, your stepping stones to the future
{% endblock %}

{% block title %}
    Register Page
{% endblock %}

{% block content %}
<div class="container" style="height: 100vh;">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <h2 class="card-title">Registration Page</h2>
                    <form method="post" action="{% url 'college_app:register' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username:</label>
                            <input type="text" class="form-control" name="username" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email ID:</label>
                            <input type="email" class="form-control" name="email" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Password:</label>
                            <input type="password" class="form-control" name="password" required>
                        </div>
                        <div class="form-group">
                            <label for="password1">Confirm Password:</label>
                            <input type="password" class="form-control" name="password1" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                    {% for msg in messages %}
                        <h2>{{ msg }}</h2>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

college_project/templates/success.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    Welcome to Appolo University your stepping stones to the future
{% endblock %}

{% block title %}
    Success!
{% endblock %}

{% block content %}
<div style="height: 100vh;">
    <h2 style="margin-bottom: 50px;">Enquiry Submitted Successfully!</h2>
    <div class="container">
        <div class="text-center" style="margin-top: 20px;">
            Return to <a href="{% url 'college_app:home' %}">home</a> page
        </div>
    </div>
</div>
{% endblock %}

college_project/templates/userinfo.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    Welcome to Appolo University, your stepping stones to the future
{% endblock %}

{% block title %}
    Welcome
{% endblock %}

{% block content %}
<div class="container" style="height: 100vh;">
    <div class="row">
        <div>
            <div class="mr-auto">
                <br><h2 class="text-center" style="margin-bottom: 15px">
                    Welcome {{user.username}}!
                </h2><br>
                <p class="text-justify">
                    As you log in to Apollo University's online platform, you step into a realm of boundless opportunities and academic excellence. Here, your educational journey is not just a path but a transformative experience designed to empower you with knowledge, skills, and insights that will shape your future.

                    At Apollo University, we believe in fostering a dynamic learning environment where curiosity thrives, creativity flourishes, and innovation knows no bounds. Whether you're embarking on a new academic endeavor, pursuing your passions, or charting your career path, our dedicated faculty and comprehensive resources are here to support you every step of the way.

                    As you navigate through our platform, you'll discover a rich tapestry of courses, programs, and extracurricular activities tailored to your interests and aspirations. From cutting-edge research initiatives to vibrant student communities, Apollo University offers a holistic educational experience that extends beyond the confines of the classroom.

                    We invite you to explore, engage, and excel as you embark on this remarkable journey with us. Together, let's unlock the doors to knowledge, seize the opportunities that lie ahead, and embrace the transformative power of education.

                    Welcome to Apollo University – where your aspirations take flight, and your dreams become reality.

                </p><br><p class="text-center"><b>If you have any enquiries let us know in the given <a href="{% url 'college_app:enquiry' %}">link</a> will reply to the enquiries within 2-3 business days.</b>
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock %}